FROM python:3.12-slim

WORKDIR /apps

COPY requirements.txt /apps/
RUN pip install --no-cache-dir -r requirements.txt

COPY app /apps/app

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--root-path", "/api"]
