services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: or8800752
      POSTGRES_DB: mydatabase
    ports:
      - "1505:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: fastapi_app
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://myuser:or8800752@postgres:5432/mydatabase
    ports:
      - "1606:8000"

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: telegram_bot
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://myuser:or8800752@postgres:5432/mydatabase
      BOT_TOKEN: "7662547349:AAGg5l2P12uZU3pWheFtgk-kwcNLWodmlBg"

  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: always
    ports:
      - "80:80"  # сайт будет доступен на http://localhost:1980
    volumes:
      - ./my-vue-app/dist:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - fastapi

volumes:
  postgres_data:
